### ISSUE TITLE
Cannot read dev,train,test files

### ISSUE THREAD

**Issue by alphamupsiomega** [davidgolub/QuestionGeneration#2]
The column names are wrong from Maluuba

The other closed issue did not address this issue: [Issue](https://github.com/Maluuba/newsqa/issues/16)

```
python -m newsqa.prepro
Preprocessing data type dev
Reading data from source path newsqa/dev.csv
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/Users/MY/anaconda/envs/py3/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2566, in get_value
    return libts.get_value_box(s, key)
  File "pandas/_libs/tslib.pyx", line 1017, in pandas._libs.tslib.get_value_box
  File "pandas/_libs/tslib.pyx", line 1025, in pandas._libs.tslib.get_value_box
TypeError: 'str' object cannot be interpreted as an integer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/MY/anaconda/envs/py3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/MY/anaconda/envs/py3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/MY/Downloads/QuestionGeneration/bidaf/newsqa/prepro.py", line 300, in <module>
    main()
  File "/Users/MY/Downloads/QuestionGeneration/bidaf/newsqa/prepro.py", line 18, in main
    prepro(args)
  File "/Users/MY/Downloads/QuestionGeneration/bidaf/newsqa/prepro.py", line 62, in prepro
    prepro_each(args, 'dev', out_name='dev')
  File "/Users/MY/Downloads/QuestionGeneration/bidaf/newsqa/prepro.py", line 156, in prepro_each
    answer_char_ranges = question_info['answer_char_ranges']
  File "/Users/MY/anaconda/envs/py3/lib/python3.6/site-packages/pandas/core/series.py", line 623, in __getitem__
    result = self.index.get_value(self, key)
  File "/Users/MY/anaconda/envs/py3/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2574, in get_value
    raise e1
  File "/Users/MY/anaconda/envs/py3/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2560, in get_value
    tz=getattr(series.dtype, 'tz', None))
  File "pandas/_libs/index.pyx", line 83, in pandas._libs.index.IndexEngine.get_value
  File "pandas/_libs/index.pyx", line 91, in pandas._libs.index.IndexEngine.get_value
  File "pandas/_libs/index.pyx", line 139, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1265, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1273, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'answer_char_ranges'
```

Even after manually changing the column names from 'answer_token_ranges' to 'answer_char_ranges', there continues to be problems parsing the column.

```
(py3) MYMBP:bidaf MY$ python -m newsqa.prepro
Preprocessing data type dev
Reading data from source path newsqa/dev.csv
Traceback (most recent call last):
  File "pandas/_libs/parsers.pyx", line 1175, in pandas._libs.parsers.TextReader._convert_tokens
  File "pandas/_libs/parsers.pyx", line 1281, in pandas._libs.parsers.TextReader._convert_with_dtype
  File "pandas/_libs/parsers.pyx", line 1297, in pandas._libs.parsers.TextReader._string_convert
  File "pandas/_libs/parsers.pyx", line 1539, in pandas._libs.parsers._string_box_utf8
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcc in position 2353: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/MY/anaconda/envs/py3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/MY/anaconda/envs/py3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/MY/Downloads/QuestionGeneration/bidaf/newsqa/prepro.py", line 300, in <module>
    main()
  File "/Users/MY/Downloads/QuestionGeneration/bidaf/newsqa/prepro.py", line 18, in main
    prepro(args)
  File "/Users/MY/Downloads/QuestionGeneration/bidaf/newsqa/prepro.py", line 62, in prepro
    prepro_each(args, 'dev', out_name='dev')
  File "/Users/MY/Downloads/QuestionGeneration/bidaf/newsqa/prepro.py", line 133, in prepro_each
    keep_default_na=False)
  File "/Users/MY/anaconda/envs/py3/lib/python3.6/site-packages/pandas/io/parsers.py", line 709, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/Users/MY/anaconda/envs/py3/lib/python3.6/site-packages/pandas/io/parsers.py", line 455, in _read
    data = parser.read(nrows)
  File "/Users/MY/anaconda/envs/py3/lib/python3.6/site-packages/pandas/io/parsers.py", line 1069, in read
    ret = self._engine.read(nrows)
  File "/Users/MY/anaconda/envs/py3/lib/python3.6/site-packages/pandas/io/parsers.py", line 1839, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 902, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 924, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 1001, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 1130, in pandas._libs.parsers.TextReader._convert_column_data
  File "pandas/_libs/parsers.pyx", line 1182, in pandas._libs.parsers.TextReader._convert_tokens
  File "pandas/_libs/parsers.pyx", line 1281, in pandas._libs.parsers.TextReader._convert_with_dtype
  File "pandas/_libs/parsers.pyx", line 1297, in pandas._libs.parsers.TextReader._string_convert
  File "pandas/_libs/parsers.pyx", line 1539, in pandas._libs.parsers._string_box_utf8
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcc in position 2353: invalid continuation byte
```

**Comment by juharris** [comment]
[Maluuba/newsqa](https://github.com/Maluuba/newsqa) has been updated to be more robust with the field processing. Please update https://github.com/Maluuba/newsqa/issues/16 if there are any more issues with the order of the fields.

As for char/token ranges. Sorry for the confusion. Char ranges were removed from the tokenized version because they aren't reliable in the tokenized version. There's an explanation here: https://github.com/Maluuba/newsqa/issues/18

I'd like to simplify the dataset by providing a JSON and JSONL versions. Stay tuned!

Thanks for the feedback!

**Comment by juharris** [comment]
I just noticed from the stack-trace that you're using Python 3. As per our [docs](https://github.com/Maluuba/newsqa#manual-set-up) Python 2 is required for the manual setup. Sorry! - that's why we have the Docker instructions so that you can prepare the dataset and then use it with whatever you need.

If you don't need the tokenized data then I suggest that you use the new [JSON format](https://github.com/Maluuba/newsqa#json).
