### ISSUE TITLE
Exceptions raised in bidaf/squad/utils.py get_2d_spans

### ISSUE THREAD

**Issue by alphamupsiomega** [davidgolub/QuestionGeneration#3]
`python3 -m newsqa.prepro`

```Traceback (most recent call last):
  File "/Users/MY/anaconda/envs/py3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/MY/anaconda/envs/py3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/MY/Downloads/QuestionGeneration/bidaf/newsqa/prepro.py", line 300, in <module>
    main()
  File "/Users/MY/Downloads/QuestionGeneration/bidaf/newsqa/prepro.py", line 18, in main
    prepro(args)
  File "/Users/MY/Downloads/QuestionGeneration/bidaf/newsqa/prepro.py", line 62, in prepro
    prepro_each(args, 'dev', out_name='dev')
  File "/Users/MY/Downloads/QuestionGeneration/bidaf/newsqa/prepro.py", line 239, in prepro_each
    yi0, yi1 = get_word_span(context, xi, answer_start, answer_stop)
  File "/Users/MY/Downloads/QuestionGeneration/bidaf/squad/utils.py", line 22, in get_word_span
    spanss = get_2d_spans(context, wordss)
  File "/Users/MY/Downloads/QuestionGeneration/bidaf/squad/utils.py", line 13, in get_2d_spans
    raise Exception()
Exception```

**Comment by paniabhisek** [comment]
Any explanation as why you are raising an Exception would be great..

@mikalyoung Did you resolve this exception. can you tell how ?

**Comment by 385628424** [comment]
解决了吗？
