### ISSUE TITLE
error with prepro.py

### ISSUE THREAD

**Issue by yexing99** [davidgolub/QuestionGeneration#5]
I met a problem when doing python3 -m newsqa.prepro   . Any suggestions?

 python3 -m newsqa.prepro                                                                                                
Traceback (most recent call last):
  File "/anaconda/envs/py35/lib/python3.5/runpy.py", line 174, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/anaconda/envs/py35/lib/python3.5/runpy.py", line 144, in _get_module_details
    code = loader.get_code(mod_name)
  File "<frozen importlib._bootstrap_external>", line 767, in get_code
  File "<frozen importlib._bootstrap_external>", line 727, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/adminye/QuestionGeneration/bidaf/newsqa/prepro.py", line 1
    version https://git-lfs.github.com/spec/v1
                ^
SyntaxError: invalid syntax

**Comment by paniabhisek** [comment]
you need to clone using `git lfs`

**Comment by sekhar14** [comment]
Its not working anymore. By any chance you have any other link from where i can download the data or the data format so that i can prepare the data. Thanks in advance
